In [1]:
import torch
torch.__version__

'1.13.1'

#### Creating Tensors

##### Scalar

In [6]:
#scalar - can be thought of as a zero-dim tensor - Notice the small `t`
scalar = torch.tensor(7)
scalar

tensor(7)

In [7]:
# getting the dimnesion
print(scalar.ndim)

0


In [8]:
print(scalar.item()) 

7

##### Vector

In [9]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [10]:
vector.ndim

1

##### Matrix

In [12]:
matrix = torch.tensor([
    [7,8], [9, 10]
])
print(matrix)
print(matrix.ndim)
print(matrix.shape)

tensor([[ 7,  8],
        [ 9, 10]])
2
torch.Size([2, 2])


##### Tensor

In [14]:
tensor = torch.tensor([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(tensor)
print(tensor.ndim, tensor.shape)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
2 torch.Size([3, 3])


In [15]:
#### Random Tensors

In [18]:
random_tensor = torch.rand(size=[3,4])
random_tensor, random_tensor.dtype

(tensor([[0.5769, 0.7000, 0.5116, 0.3510],
         [0.7427, 0.1535, 0.5119, 0.9307],
         [0.7289, 0.1810, 0.8795, 0.4748]]),
 torch.float32)

In [19]:
### zero and one tensors
zero = torch.zeros(size=(3,4))
ones = torch.ones(size=(3,4))
zero, ones, zero.shape, ones.shape

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.Size([3, 4]),
 torch.Size([3, 4]))

In [21]:
#### Creating a tensor with range of values

In [22]:
# creating a range from 0 to 10
z_to_t = torch.arange(start=0, end=10, step=1)
z_to_t

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
### Using zeros_like 
ten_zeros = torch.zeros_like(input=z_to_t)
ten_zeros_alt = torch.zeros(size=z_to_t.shape)
ten_zeros, ten_zeros_alt, ten_zeros.dtype, ten_zeros_alt.dtype, z_to_t.shape

(tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 torch.int64,
 torch.float32,
 torch.Size([10]))

In [27]:
## Note: above when using torch.zeros the default type is float32, to make the above to function
# calls alike we will need to explicitly specify the dtype

In [30]:
ten_zeros_alt = torch.zeros(size=z_to_t.shape, dtype=torch.int64)
assert torch.equal(ten_zeros, ten_zeros_alt)

In [31]:
### Understanding generic tensor in pytorch

In [34]:
# default type for tensor is float32
float32_tensor = torch.tensor([3.0, 6.0, 9.0],
dtype=None,          # default is torch.float32
device=None,         # default to None, which uses the default tensor type
requires_grad=False) # if True, the operations performed on the tensor are recorded

float32_tensor.shape, float32_tensor.dtype, float32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))