In [3]:
import torch
torch.__version__

'1.13.1'

#### Creating Tensors

##### Scalar

In [6]:
#scalar - can be thought of as a zero-dim tensor - Notice the small `t`
scalar = torch.tensor(7)
scalar

tensor(7)

In [7]:
# getting the dimnesion
print(scalar.ndim)

0


In [8]:
print(scalar.item()) 

7

##### Vector

In [9]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [10]:
vector.ndim

1

##### Matrix

In [12]:
matrix = torch.tensor([
    [7,8], [9, 10]
])
print(matrix)
print(matrix.ndim)
print(matrix.shape)

tensor([[ 7,  8],
        [ 9, 10]])
2
torch.Size([2, 2])


##### Tensor

In [14]:
tensor = torch.tensor([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(tensor)
print(tensor.ndim, tensor.shape)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
2 torch.Size([3, 3])


In [15]:
#### Random Tensors

In [18]:
random_tensor = torch.rand(size=[3,4])
random_tensor, random_tensor.dtype

(tensor([[0.5769, 0.7000, 0.5116, 0.3510],
         [0.7427, 0.1535, 0.5119, 0.9307],
         [0.7289, 0.1810, 0.8795, 0.4748]]),
 torch.float32)

In [19]:
### zero and one tensors
zero = torch.zeros(size=(3,4))
ones = torch.ones(size=(3,4))
zero, ones, zero.shape, ones.shape

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.Size([3, 4]),
 torch.Size([3, 4]))

In [21]:
#### Creating a tensor with range of values

In [22]:
# creating a range from 0 to 10
z_to_t = torch.arange(start=0, end=10, step=1)
z_to_t

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
### Using zeros_like 
ten_zeros = torch.zeros_like(input=z_to_t)
ten_zeros_alt = torch.zeros(size=z_to_t.shape)
ten_zeros, ten_zeros_alt, ten_zeros.dtype, ten_zeros_alt.dtype, z_to_t.shape

(tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 torch.int64,
 torch.float32,
 torch.Size([10]))

In [27]:
## Note: above when using torch.zeros the default type is float32, to make the above to function
# calls alike we will need to explicitly specify the dtype

In [30]:
ten_zeros_alt = torch.zeros(size=z_to_t.shape, dtype=torch.int64)
assert torch.equal(ten_zeros, ten_zeros_alt)

In [31]:
### Understanding generic tensor in pytorch

In [4]:
# default type for tensor is float32
float32_tensor = torch.tensor([3.0, 6.0, 9.0],
dtype=None,          # default is torch.float32
device=None,         # default to None, which uses the default tensor type
requires_grad=False) # if True, the operations performed on the tensor are recorded

float32_tensor.shape, float32_tensor.dtype, float32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [5]:
float16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float16)

#### Manipulating tensors

In [11]:
# Creating a tensor and adding a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [8]:
# Creating a tensor and multiplying a num
# Also , note: the value within the tensor wont change unless re-assigned.
tensor * 10

tensor([10, 20, 30])

In [12]:
# subtract a number with re-assignment
tensor = tensor - 10
print(tensor)
tensor = tensor + 10
print(tensor)

tensor([-9, -8, -7])
tensor([1, 2, 3])


In [13]:
### Using torch built-in for the above

In [14]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [15]:
torch.subtract(tensor, 10)

tensor([-9, -8, -7])

In [16]:
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [ ]:
### Matrix Multiplication

In [17]:
# Element wise multiplication
tensor * tensor

tensor([1, 4, 9])

In [22]:
# Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [27]:
t1 = torch.rand([2,3])
t2 = torch.rand([3,2])
t1, t2

(tensor([[0.1193, 0.3873, 0.6569],
         [0.9427, 0.8883, 0.7520]]),
 tensor([[0.4145, 0.7897],
         [0.8818, 0.1247],
         [0.4893, 0.1776]]))

In [29]:
t3 = torch.matmul(t1, t2)
t3

tensor([[0.7123, 0.2591],
        [1.5420, 0.9888]])

In [30]:
%%time
# Matrix Multiplication
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
value

CPU times: user 623 µs, sys: 1.01 ms, total: 1.63 ms
Wall time: 1.65 ms


tensor(14)

In [31]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 176 µs, sys: 206 µs, total: 382 µs
Wall time: 335 µs


tensor(14)

In [ ]:
### Linear Fully Connected Layer 
#y = Ax + b

In [32]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

In [33]:
torch.manual_seed(42)
linear = torch.nn.Linear(in_features=2,  # matches inner dimension of input
                        out_features=6)  # describes outer value

x = tensor_A
output = linear(x)
print(f"Input Shape : {x.shape}\n")
print(f"Output:\n{output}\nOutput shape: {output.shape}")

Input Shape : torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)
Output shape: torch.Size([3, 6])


In [34]:
## Finding min, max, mean and sum (aggregation)

In [37]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [38]:
print(f"Minimum : {x.min()}")
print(f"Maximum : {x.max()}")
print(f"Mean    : {x.type(torch.float32).mean()}") # note: we need to change type here to float32 to make it work
print(f"Sum     : {x.sum()}")

Minimum : 0
Maximum : 90


RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long